name: Lint and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint flake8 black isort mypy pytest pytest-cov
    
    - name: Run Black (code formatter)
      run: |
        black --check --diff project/
    
    - name: Run isort (import sorter)
      run: |
        isort --check-only --diff project/
    
    - name: Run Pylint
      run: |
        pylint project/ --fail-under=7.0
    
    - name: Run Flake8
      run: |
        flake8 project/ --max-line-length=100
    
    - name: Run MyPy (type checker)
      run: |
        mypy project/ --ignore-missing-imports
    
    - name: Run tests
      run: |
        pytest tests/ -v --cov=project --cov-report=xml || echo "No tests found"
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false 