name : implement github action for training and testing

on : 
  push:
    branches: 
      - main


jobs: 
  My-deploy-job : 
    runs-on : ubuntu-latest

    steps : 
      - name : checkout code
        run : echo "hello world"